


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package StreamWriter_axi4stream_vip_0_0_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter StreamWriter_axi4stream_vip_0_0_VIP_INTERFACE_MODE     = 0;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_SIGNAL_SET         = 8'b00010011;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_DATA_WIDTH         = 32;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_ID_WIDTH           = 0;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_DEST_WIDTH         = 0;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_USER_WIDTH         = 0;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_USER_BITS_PER_BYTE = 0;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_HAS_TREADY         = 1;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_HAS_TSTRB          = 0;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_HAS_TKEEP          = 0;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_HAS_TLAST          = 1;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_HAS_ACLKEN         = 0;
      parameter StreamWriter_axi4stream_vip_0_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi4stream_mst_agent #(StreamWriter_axi4stream_vip_0_0_VIP_SIGNAL_SET, 
                        StreamWriter_axi4stream_vip_0_0_VIP_DEST_WIDTH,
                        StreamWriter_axi4stream_vip_0_0_VIP_DATA_WIDTH,
                        StreamWriter_axi4stream_vip_0_0_VIP_ID_WIDTH,
                        StreamWriter_axi4stream_vip_0_0_VIP_USER_WIDTH, 
                        StreamWriter_axi4stream_vip_0_0_VIP_USER_BITS_PER_BYTE,
                        StreamWriter_axi4stream_vip_0_0_VIP_HAS_ARESETN) StreamWriter_axi4stream_vip_0_0_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      StreamWriter_axi4stream_vip_0_0_mst_t  StreamWriter_axi4stream_vip_0_0_mst;
//      initial begin : START_StreamWriter_axi4stream_vip_0_0_MASTER
//        StreamWriter_axi4stream_vip_0_0_mst = new("StreamWriter_axi4stream_vip_0_0_mst", `StreamWriter_axi4stream_vip_0_0_PATH_TO_INTERFACE);
//        StreamWriter_axi4stream_vip_0_0_mst.start_master();
//      end



endpackage : StreamWriter_axi4stream_vip_0_0_pkg
